# Generated by Django 3.1.2 on 2020-10-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progs',
            name='status',
            field=models.CharField(default='not_runned', max_length=200),
        ),
        migrations.AddField(
            model_name='runtime',
            name='no_err_text',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
