# Generated by Django 3.1.2 on 2020-10-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201031_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='progs',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
