# Generated by Django 3.1.2 on 2020-10-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_progs_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progs',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
