# Generated by Django 3.1.2 on 2020-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201031_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='runtime',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syntax',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='syntax',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='err_text',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
